language: php
dist: trusty
sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"

before_install:
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose validate
  - composer --verbose install

script:
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drush site-install webship --yes --site-name='Webship' --verbose --db-url=sqlite://tmp/site.sqlite
  - ./../vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
  - until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null
  - ./../vendor/bin/phpunit -c core --testsuite unit --exclude-group Composer,DependencyInjection,PageCache,Setup
  - ./../vendor/bin/drush
  - if [[ $RELEASE = stable ]]; then ./../vendor/bin/drupal; fi;
