# DDEV configuration of a Webship project.
# The project name defaults to the directory name. See https://docs.ddev.com
type: drupal
docroot: web
php_version: "8.4"
webserver_type: apache-fpm
database:
  type: mysql
  version: "8.0"
composer_version: "2"
nodejs_version: "22"
corepack_enable: false
mutagen_enabled: false
use_dns_when_possible: true
project_tld: ddev.site
web_environment:
  - DRUSH_OPTIONS_URI=$DDEV_PRIMARY_URL
